# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVaultScg < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.9/aws-vault-scg_0.0.9_Darwin_amd64.tar.gz"
      sha256 "61d658b8cc5c84e8b0a622d0d631bf8817f0eac05a40a34a4e7800819b8996d6"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.9/aws-vault-scg_0.0.9_Darwin_arm64.tar.gz"
      sha256 "a4a6ea088216e01618a3bcef95631555efac092885795a9f0ad7c4645e35017e"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.9/aws-vault-scg_0.0.9_Linux_arm64.tar.gz"
      sha256 "8b80e2b2061ec289c69905aae2bd265165d6f3578f64366070ffe82e87885366"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.9/aws-vault-scg_0.0.9_Linux_amd64.tar.gz"
      sha256 "1850e361e6095f61d5e568d100f1c19b0081081c1687b0595e73ac5f8d88d3f9"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end
end
