# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVaultScg < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.8/aws-vault-scg_0.0.8_Darwin_amd64.tar.gz"
      sha256 "046073a15cf28ce8912347878288f70bcdd40dba12da1aef3d7392300ed875ef"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.8/aws-vault-scg_0.0.8_Darwin_arm64.tar.gz"
      sha256 "cbf9188e04164429cb925c99a37bc492bf799a20a1db34a5f6a06440aa8d6ea3"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.8/aws-vault-scg_0.0.8_Linux_arm64.tar.gz"
      sha256 "1ad576cfea54cde8f11649749db21669820c4876ebc83bf88686fdfd2473aeaa"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.8/aws-vault-scg_0.0.8_Linux_amd64.tar.gz"
      sha256 "d65db6dad40c088277c8c044b74cfbf5c49eb1a286c7a0ddf89b0547d9987e23"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end
end
