# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVaultScg < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.7/aws-vault-scg_0.0.7_Darwin_amd64.tar.gz"
      sha256 "bc0148116813a715873084a9219520501ddc9e90180b5b5e9d7e5c09aa4a955d"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.7/aws-vault-scg_0.0.7_Darwin_arm64.tar.gz"
      sha256 "de89a51a7af9c35f796197a31ea864b8be0bec87eb36d06e30f975751195a5f8"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.7/aws-vault-scg_0.0.7_Linux_amd64.tar.gz"
      sha256 "4a356b538769b697575a8d79e21040eed8cd1536ecced5779a1ab1293eb8c89d"

      def install
        bin.install "aws-vault-scg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gympass/aws-vault-scg/releases/download/v0.0.7/aws-vault-scg_0.0.7_Linux_arm64.tar.gz"
      sha256 "926a3b61fe19a4ae7277f6694f2da7845eb9f77815e208f8fd655611485a3c9a"

      def install
        bin.install "aws-vault-scg"
      end
    end
  end
end
