# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bic < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gympass/backup-integrity-checker/releases/download/0.1.0/macOS_bic_arm64.tar.gz"
      sha256 "dd9dcbed2ad4642a822913448228779b571649728350f83b5531200b4f83ee5c"

      def install
        bin.install "bic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gympass/backup-integrity-checker/releases/download/0.1.0/macOS_bic_64-bit.tar.gz"
      sha256 "9d8fb59cb6031da4945782a3c95b2c8c4f8ced9d90befd9ff8400aea39713db1"

      def install
        bin.install "bic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gympass/backup-integrity-checker/releases/download/0.1.0/Linux_bic_arm64.tar.gz"
      sha256 "639d58751e68e5b6260744850c2913b0aab73cc5c552150afac3a049856b4465"

      def install
        bin.install "bic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gympass/backup-integrity-checker/releases/download/0.1.0/Linux_bic_64-bit.tar.gz"
      sha256 "90993b55d6fcadd1d4bf63ed6f9a4199f4fe804f7b2b68508e58b27d574e9bb1"

      def install
        bin.install "bic"
      end
    end
  end
end
