# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bic < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gympass/backup-integrity-resource/releases/download/0.1.0/bic_0.1.0_macOS_arm64.tar.gz"
      sha256 "dbc9b3a752deca918f7f56e8d4a3777d403cebdbb6f896ee052d6dd51a81b39c"

      def install
        bin.install "bic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gympass/backup-integrity-resource/releases/download/0.1.0/bic_0.1.0_macOS_64-bit.tar.gz"
      sha256 "2ea816e80ef41915ffb62ab42e47f734b4c61fbd4d2a0873c02927d17c4c57ce"

      def install
        bin.install "bic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gympass/backup-integrity-resource/releases/download/0.1.0/bic_0.1.0_Linux_arm64.tar.gz"
      sha256 "049c4fdd99a84cae0f523a66d5cb73f8b6ea4a6be9fee777e618a6e4f5db34d9"

      def install
        bin.install "bic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gympass/backup-integrity-resource/releases/download/0.1.0/bic_0.1.0_Linux_64-bit.tar.gz"
      sha256 "4fdbbd6f89f956c34f7d9d3b47da00ab68656a2506b3c5bc46e8e01436bdc61b"

      def install
        bin.install "bic"
      end
    end
  end
end
